import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  modalContainer: {
    flex: 1,
    position: "relative",
    justifyContent: "flex-end",
    paddingHorizontal: 0,
    paddingTop: 16,
  },
  noteSheetOverlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: "flex-end",
  },
  noteSheetBackdrop: {
    ...StyleSheet.absoluteFillObject,
  },
  noteSheetContainer: {
    flex: 1,
    justifyContent: "flex-end",
    paddingTop: 16,
  },
  sheet: {
    width: "100%",
    maxWidth: 560,
    alignSelf: "center",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    paddingTop: 8,
    paddingHorizontal: 16,
    paddingBottom: 24,
    gap: 10,
  },
  dragHandleWrap: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 2,
  },
  dragHandle: {
    width: 40,
    height: 4,
    borderRadius: 999,
  },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  iconButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  controlRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  typeSwitch: {
    flexDirection: "row",
    borderRadius: 14,
    padding: 3,
    gap: 4,
    borderWidth: 1,
  },
  typeButton: {
    minWidth: 58,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  metaControlRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    flexShrink: 1,
  },
  metaChip: {
    minWidth: 72,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 12,
    borderWidth: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
  },
  amountPanel: {
    borderRadius: 18,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 10,
    gap: 8,
  },
  amountRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  amountCurrency: {
    minWidth: 20,
  },
  amountValue: {
    flex: 1,
    textAlign: "right",
  },
  messageBanner: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  categorySection: {
    gap: 8,
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  categoryScroll: {
    flexGrow: 0,
  },
  categoryRow: {
    flexDirection: "row",
    gap: 8,
    paddingRight: 12,
    alignItems: "center",
  },
  categoryChip: {
    minHeight: 38,
    borderRadius: 12,
    borderWidth: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 8,
    paddingVertical: 6,
  },
  categoryIconWrapSm: {
    width: 22,
    height: 22,
    borderRadius: 11,
    alignItems: "center",
    justifyContent: "center",
  },
  footerBlock: {
    gap: 8,
  },
  paymentMethodRow: {
    gap: 8,
    paddingRight: 12,
  },
  paymentMethodChip: {
    minHeight: 36,
    borderRadius: 12,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 6,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  paymentMethodBadge: {
    width: 20,
    height: 20,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  noteSheetInput: {
    minHeight: 120,
    textAlignVertical: "top",
    paddingTop: 12,
  },
  noteDisplay: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 12,
    borderWidth: 1,
  },
  keypadLayout: {
    flexDirection: "row",
    gap: 8,
  },
  keypadGrid: {
    flex: 1,
    gap: 8,
  },
  keypadRow: {
    flexDirection: "row",
    gap: 8,
  },
  keypadButton: {
    flex: 1,
    height: 50,
    borderRadius: 16,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  keypadSpacer: {
    flex: 1,
  },
  keypadRail: {
    width: 84,
    gap: 8,
  },
  railButton: {
    height: 50,
    borderRadius: 16,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  saveButton: {
    flex: 1,
    minHeight: 108,
    borderRadius: 18,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 8,
  },
  dialogHeroCard: {
    borderRadius: 18,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  dialogHeroIcon: {
    width: 42,
    height: 42,
    borderRadius: 14,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  dialogHeroCopy: {
    flex: 1,
    gap: 2,
  },
  dialogSection: {
    gap: 8,
  },
  shortcutRow: {
    flexDirection: "row",
    gap: 8,
  },
  shortcutCard: {
    flex: 1,
    minHeight: 68,
    borderRadius: 16,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 10,
    gap: 2,
    justifyContent: "center",
  },
  calendarPanel: {
    borderRadius: 18,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 12,
    gap: 8,
  },
  calendarHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  calendarNavButton: {
    width: 34,
    height: 34,
    borderRadius: 17,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  weekRow: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  weekCell: {
    width: 40,
    textAlign: "center",
    marginBottom: 4,
  },
  dayCell: {
    width: 40,
    height: 44,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    marginVertical: 2,
    borderWidth: 1,
  },
  todayMarker: {
    position: "absolute",
    bottom: 6,
    width: 5,
    height: 5,
    borderRadius: 999,
  },
  timePresetRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  timePresetCard: {
    minWidth: 88,
    flexGrow: 1,
    borderRadius: 16,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 10,
    gap: 3,
  },
  timePickerContent: {
    flexDirection: "row",
    gap: 12,
  },
  timeColumn: {
    flex: 1,
    borderRadius: 18,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 10,
    gap: 8,
  },
  timeSectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  timeOptionsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  timeGridChip: {
    width: 40,
    minHeight: 40,
    borderRadius: 12,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
  },
});
